version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
    environment:
      - DB_URL=value
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=exemple
      - POSTGRES_USER=exemple
    volumes:
      - ./database_volume:/var/lib/postgresql/data

volumes:
  database_volume:
